Homework3
Kryschtop/EasyIT-course pull request #3
Opened 2020-09-06 13:01 UTC by Kryschtop

2020-09-06 18:03 UTC, bloodybaker requested changes
Комментарии оставил. Жду исправлений

2020-09-06 18:03 UTC, bloodybaker commented on src/com/company/task2/Friend.java
> +public class Friend {
Друг - тоже человек, унаследуйте его

2020-09-06 18:03 UTC, bloodybaker commented on src/com/company/task2/Friend.java
> +
Друг тоже должен иметь хобби

2020-09-06 18:03 UTC, bloodybaker commented on src/com/company/task2/Girl.java
> +import sun.text.normalizer.CharTrie;
Лишнее

2020-09-06 18:03 UTC, bloodybaker commented on src/com/company/task2/Main.java
> +        Boy boy = new Boy("Oks",25,178,76,friend2);
Не создавайте объекты, а лучше передайте конструктор в конструкторе (не создавайте объект если не будете его использовать)

2020-09-06 21:10 UTC, bloodybaker requested changes
Внесите исправления. Уже лучше

2020-09-06 21:10 UTC, bloodybaker commented on src/com/company/task2/Friend.java
> +    private Hobby hobby;
Уберите хобби с классов Friend, Girl и Boy ибо оно там повторяется. Вынесите его в базовый класс(Human) и передавайте через дочерний конструктор

2020-09-06 21:10 UTC, bloodybaker commented on src/com/company/task2/Humen.java
> +}
2 одинаковых метода. Можно их заменить одним (Переопределите toString)

2020-09-06 21:12 UTC, bloodybaker commented
Я уже проревьювил. Внесите изменения в код

2020-09-06 21:12 UTC, Kryschtop commented on src/com/company/task2/Humen.java
> +}
Хорошо,спасибо

2020-09-07 16:01 UTC, bloodybaker approved these changes

2020-09-07 16:01 UTC, merged